---

_You are currently looking at **version 1.1** of this notebook. To download notebooks and datafiles, as well as get help on Jupyter notebooks in the Coursera platform, visit the [Jupyter Notebook FAQ](https://www.coursera.org/learn/python-data-analysis/resources/0dhYG) course resource._

---

In [38]:
import pandas as pd
import numpy as np
import re
from scipy.stats import ttest_ind

# Assignment 4 - Hypothesis Testing
This assignment requires more individual learning than previous assignments - you are encouraged to check out the [pandas documentation](http://pandas.pydata.org/pandas-docs/stable/) to find functions or methods you might not have used yet, or ask questions on [Stack Overflow](http://stackoverflow.com/) and tag them as pandas and python related. And of course, the discussion forums are open for interaction with your peers and the course staff.

Definitions:
* A _quarter_ is a specific three month period, Q1 is January through March, Q2 is April through June, Q3 is July through September, Q4 is October through December.
* A _recession_ is defined as starting with two consecutive quarters of GDP decline, and ending with two consecutive quarters of GDP growth.
* A _recession bottom_ is the quarter within a recession which had the lowest GDP.
* A _university town_ is a city which has a high percentage of university students compared to the total population of the city.

**Hypothesis**: University towns have their mean housing prices less effected by recessions. Run a t-test to compare the ratio of the mean price of houses in university towns the quarter before the recession starts compared to the recession bottom. (`price_ratio=quarter_before_recession/recession_bottom`)

The following data files are available for this assignment:
* From the [Zillow research data site](http://www.zillow.com/research/data/) there is housing data for the United States. In particular the datafile for [all homes at a city level](http://files.zillowstatic.com/research/public/City/City_Zhvi_AllHomes.csv), ```City_Zhvi_AllHomes.csv```, has median home sale prices at a fine grained level.
* From the Wikipedia page on college towns is a list of [university towns in the United States](https://en.wikipedia.org/wiki/List_of_college_towns#College_towns_in_the_United_States) which has been copy and pasted into the file ```university_towns.txt```.
* From Bureau of Economic Analysis, US Department of Commerce, the [GDP over time](http://www.bea.gov/national/index.htm#gdp) of the United States in current dollars (use the chained value in 2009 dollars), in quarterly intervals, in the file ```gdplev.xls```. For this assignment, only look at GDP data from the first quarter of 2000 onward.

Each function in this assignment below is worth 10%, with the exception of ```run_ttest()```, which is worth 50%.

In [311]:
# Use this dictionary to map state names to two letter acronyms
states = {'OH': 'Ohio', 'KY': 'Kentucky', 'AS': 'American Samoa', 'NV': 'Nevada', 'WY': 'Wyoming', 'NA': 'National', 'AL': 'Alabama', 'MD': 'Maryland', 'AK': 'Alaska', 'UT': 'Utah', 'OR': 'Oregon', 'MT': 'Montana', 'IL': 'Illinois', 'TN': 'Tennessee', 'DC': 'District of Columbia', 'VT': 'Vermont', 'ID': 'Idaho', 'AR': 'Arkansas', 'ME': 'Maine', 'WA': 'Washington', 'HI': 'Hawaii', 'WI': 'Wisconsin', 'MI': 'Michigan', 'IN': 'Indiana', 'NJ': 'New Jersey', 'AZ': 'Arizona', 'GU': 'Guam', 'MS': 'Mississippi', 'PR': 'Puerto Rico', 'NC': 'North Carolina', 'TX': 'Texas', 'SD': 'South Dakota', 'MP': 'Northern Mariana Islands', 'IA': 'Iowa', 'MO': 'Missouri', 'CT': 'Connecticut', 'WV': 'West Virginia', 'SC': 'South Carolina', 'LA': 'Louisiana', 'KS': 'Kansas', 'NY': 'New York', 'NE': 'Nebraska', 'OK': 'Oklahoma', 'FL': 'Florida', 'CA': 'California', 'CO': 'Colorado', 'PA': 'Pennsylvania', 'DE': 'Delaware', 'NM': 'New Mexico', 'RI': 'Rhode Island', 'MN': 'Minnesota', 'VI': 'Virgin Islands', 'NH': 'New Hampshire', 'MA': 'Massachusetts', 'GA': 'Georgia', 'ND': 'North Dakota', 'VA': 'Virginia'}

city_level_homes = pd.DataFrame.from_csv('City_Zhvi_AllHomes.csv').replace({'State':states})

GDP = pd.read_excel('gdplev.xls',skiprows=5,parse_cols='E:G')

GDP=GDP.drop(GDP.index[0:214])

GDP=GDP.rename(columns={'Unnamed: 0':'Quarter'})

GDP = GDP.set_index('Quarter')

In [330]:
def get_list_of_university_towns():
    '''Returns a DataFrame of towns and the states they are in from the 
    university_towns.txt list. The format of the DataFrame should be:
    DataFrame( [ ["Michigan", "Ann Arbor"], ["Michigan", "Yipsilanti"] ], 
    columns=["State", "RegionName"]  )
    
    The following cleaning needs to be done:

    1. For "State", removing characters from "[" to the end.
    2. For "RegionName", when applicable, removing every character from " (" to the end.
    3. Depending on how you read the data, you may need to remove newline character '\n'. '''
    
    
    univ_towns = {}
    with open('university_towns.txt','r') as univ_file:
        for line in univ_file:
            if '[edit]' in line:
                key = line
                key = key.split('[',1)[0].rstrip()
                continue
            else:
                line = re.sub(r'\[.*?\]','',line)
                line = re.sub(r'\(.*?\)','',line)
                line = line.split(',',1)[0].rstrip()
                univ_towns[line] = key
        univ_series = pd.Series(univ_towns, name='State')
        univ_df = univ_series.to_frame()
        univ_df = univ_df.reset_index()
        univ_df = univ_df.rename(columns={'index':'RegionName'})
        univ_df = univ_df[['State','RegionName']].sort_values(by='State')
    return univ_df

get_list_of_university_towns()

             State           RegionName
295        Alabama           Montevallo
25         Alabama               Auburn
440        Alabama           Tuscaloosa
224        Alabama         Jacksonville
441        Alabama             Tuskegee
257        Alabama           Livingston
148         Alaska            Fairbanks
437        Arizona               Tucson
431        Arizona                Tempe
160        Arizona            Flagstaff
157       Arkansas         Fayetteville
267       Arkansas             Magnolia
103       Arkansas               Conway
297       Arkansas           Monticello
382       Arkansas         Russellville
397       Arkansas               Searcy
21        Arkansas          Arkadelphia
229       Arkansas            Jonesboro
356     California               Pomona
370     California             Redlands
89      California                Chico
345     California            Palo Alto
467     California             Westwood
38      California             Berkeley
445     California      University Park
469     California             Whittier
90      California            Claremont
439     California              Turlock
377     California            Riverside
284     California               Merced
..             ...                  ...
169       Virginia       Fredericksburg
263       Virginia            Lynchburg
138     Washington           Ellensburg
35      Washington           Bellingham
85      Washington               Cheney
444     Washington  University District
366     Washington              Pullman
180  West Virginia            Glenville
402  West Virginia        Shepherdstown
463  West Virginia         West Liberty
300  West Virginia           Morgantown
216  West Virginia           Huntington
296  West Virginia           Montgomery
60   West Virginia           Buckhannon
151  West Virginia             Fairmont
23   West Virginia               Athens
376      Wisconsin          River Falls
241      Wisconsin            La Crosse
134      Wisconsin           Eau Claire
19       Wisconsin             Appleton
422      Wisconsin        Stevens Point
290      Wisconsin            Milwaukee
283      Wisconsin            Menomonie
468      Wisconsin           Whitewater
456      Wisconsin             Waukesha
352      Wisconsin          Platteville
266      Wisconsin              Madison
189      Wisconsin            Green Bay
342      Wisconsin              Oshkosh
247        Wyoming              Laramie

[485 rows x 2 columns]

In [313]:
def get_recession_start():
    '''Returns the year and quarter of the recession start time as a 
    string value in a format such as 2005q3'''
    for quarter in range(len(GDP.index)):
        if (GDP.iloc[quarter,1] > GDP.iloc[quarter+1,1]) & (GDP.iloc[quarter+1,1] > GDP.iloc[quarter+2,1]):
            recession_start = GDP.iloc[quarter].name
            break
    return recession_start

get_recession_start()

'2008q2'

In [314]:
def get_recession_end():
    '''Returns the year and quarter of the recession end time as a 
    string value in a format such as 2005q3'''
    recession_start_id = GDP.index.get_loc(get_recession_start())
    quarter = recession_start_id
    while quarter <= len(GDP.index):
        if (GDP.iloc[quarter,1] < GDP.iloc[quarter+1,1]) & (GDP.iloc[quarter+1,1] < GDP.iloc[quarter+2,1]):
            recession_end = GDP.iloc[quarter].name
            break
        quarter += 1
    return recession_end

get_recession_end()

'2009q2'

In [315]:
def get_recession_bottom():
    '''Returns the year and quarter of the recession bottom time as a 
    string value in a format such as 2005q3'''
    recession_start_id = GDP.index.get_loc(get_recession_start())
    recession_end_id = GDP.index.get_loc(get_recession_end())
    search_frame = GDP[recession_start_id:(recession_end_id+1)]
    recession_bottom = search_frame[['GDP in billions of current dollars']].idxmin(0)
    return recession_bottom[0]

get_recession_bottom()

'2009q2'

In [338]:
def convert_housing_data_to_quarters():
    '''Converts the housing data to quarters and returns it as mean 
    values in a dataframe. This dataframe should be a dataframe with
    columns for 2000q1 through 2016q3, and should have a multi-index
    in the shape of ["State","RegionName"].
    
    Note: Quarters are defined in the assignment description, they are
    not arbitrary three month periods.
    
    The resulting dataframe should have 67 columns, and 10,730 rows.
    '''
    city_level_homes.iloc[:,50].name
    city_level_recession = city_level_homes.iloc[:,city_level_homes.columns.get_loc('2000-01'):]
    city_level_recession = city_level_recession.join(city_level_homes[['RegionName','State']]).sort_values('State')
    city_level_recession = city_level_recession.set_index(['State','RegionName']).fillna(0)
    
    
    for column in city_level_recession:
        year = column.split('-')[0]
        month = column.split('-')[1]
        if 1 <= int(month) <= 3:
            quarter = 'q1'
        elif 4 <= int(month) <= 6:
            quarter = 'q2'
        elif 7 <= int(month) <= 9:
            quarter = 'q3'
        else:
            quarter = 'q4'
        year_quarter = year + quarter
        if year_quarter in city_level_recession.columns:
            city_level_recession[year_quarter] += city_level_recession[column]
        else:
            city_level_recession[year_quarter] = city_level_recession[column]
        city_level_recession.drop(column,axis=1,inplace=True)
    
    city_level_recession = city_level_recession.replace(0,np.nan)
    return city_level_recession

convert_housing_data_to_quarters()

                               2000q1    2000q2    2000q3    2000q4    2001q1  \
State     RegionName
Alabama   Mulga                   NaN       NaN       NaN       NaN       NaN
          Trussville         493200.0  497700.0  502800.0  509300.0  517600.0
          Satsuma            265800.0  272900.0  271000.0  268800.0  270700.0
          Irvington          217400.0  222300.0  227100.0  228800.0  228900.0
          Mount Olive        319500.0  322000.0  320900.0  321600.0  324800.0
          Dauphin Island     533100.0  529400.0  531400.0  531600.0  534400.0
          Tuscaloosa         313500.0  318100.0  325500.0  326300.0  329700.0
          Pleasant Grove     330000.0  330700.0  327000.0  333500.0  334400.0
          Edgewater               NaN       NaN       NaN       NaN       NaN
          Robertsdale        260500.0  263000.0  267000.0  273300.0  283100.0
          Elmore                  NaN       NaN       NaN       NaN       NaN
          Crane Hill              NaN       NaN       NaN       NaN       NaN
          Morris             372200.0  373500.0  372700.0  377400.0  376700.0
          Guntersville       278800.0  280500.0  280800.0  281900.0  282400.0
          Hope Hull          335000.0  335400.0  338900.0  343900.0  345800.0
          Elberta            404100.0  441100.0  441500.0  436100.0  436600.0
          Alabaster          366400.0  369200.0  369500.0  371100.0  369700.0
          Holly Pond              NaN       NaN       NaN       NaN       NaN
          Mount Vernon       148600.0  157300.0  153600.0  152700.0  152900.0
          Union Grove        262500.0  256700.0  255700.0  265200.0  266300.0
          Hoover             554900.0  559100.0  561600.0  567600.0  572300.0
          Center Point       242900.0  243700.0  244500.0  246700.0  250100.0
          Seminole           341200.0  369900.0  385100.0  382900.0  391300.0
          Chalkville         282300.0  283300.0  283300.0  283300.0  288200.0
          Priceville              NaN       NaN       NaN       NaN       NaN
          Hazel Green             NaN       NaN       NaN       NaN       NaN
          Summerdale         273800.0  274300.0  289900.0  300000.0  308300.0
          Calera             326800.0  331100.0  324000.0  323800.0  328000.0
          Vance              299700.0  309300.0  316100.0  318000.0  324500.0
          Ralph              372500.0  380300.0  387700.0  395500.0  399700.0
...                               ...       ...       ...       ...       ...
Wisconsin Menomonee Falls    473200.0  463600.0  457100.0  465500.0  490300.0
          Brookfield         596100.0  586000.0  578600.0  591000.0  625400.0
          Oak Creek          288200.0  298200.0  314200.0  326000.0  337400.0
          Barton                  NaN       NaN       NaN       NaN       NaN
          Roxbury            566400.0  587600.0  597700.0  591900.0  610300.0
          Cambria            271300.0  273400.0  273800.0  269300.0  270300.0
          Geneva             286400.0  265800.0  253300.0  257700.0  262400.0
          Sturtevant         238400.0  232900.0  236000.0  246100.0  258100.0
          Medina             519200.0  528700.0  528500.0  541000.0  553900.0
          Osborn             295000.0  288600.0  296000.0  311200.0  330800.0
          Sugar Creek        222500.0  207300.0  198200.0  196000.0  203700.0
          Utica              304800.0  312000.0  329100.0  345300.0  354500.0
          Rock               296800.0  301100.0  299700.0  303700.0  321600.0
          Eaton              332300.0  344800.0  364400.0  378700.0  422500.0
          Town of Eagle      507500.0  501800.0  496000.0  504100.0  527700.0
          Wales                   NaN       NaN       NaN       NaN       NaN
          Lisbon             599200.0  584100.0  576400.0  590100.0  625200.0
          Holmen                  NaN       NaN       NaN       NaN       NaN
          Holland            453100.0  451500.0  459700.0  467500.0  485600.0
          Lawrence           372200.0  384700.0  403400.0  413700.0  463300.0
          Whitelaw           288100.0  304300.0  324100.0  342000.0  349000.0
          Town of West Bend  382400.0  381700.0  379200.0  381300.0  388000.0
          Dunn               523900.0  529200.0  530200.0  542500.0  553400.0
          Bristol            528300.0  543500.0  555700.0  577000.0  589700.0
Wyoming   Casper             267700.0  268800.0  269200.0  279500.0  286500.0
          Burns              304600.0  313700.0  325100.0  339000.0  347500.0
          Pine Bluffs        281200.0  285200.0  283900.0  294200.0  309700.0
          Cheyenne           350600.0  360100.0  364600.0  370900.0  376600.0
          Evansville         384100.0  386300.0  392500.0  396200.0  391700.0
          Bar Nunn           279100.0  269000.0  266700.0  280500.0  296500.0

                               2001q2    2001q3    2001q4    2002q1    2002q2  \
State     RegionName
Alabama   Mulga                   NaN       NaN       NaN       NaN       NaN
          Trussville         520300.0  522500.0  530100.0  534000.0  542400.0
          Satsuma            272300.0  271900.0  276600.0  279000.0  279600.0
          Irvington          222900.0  220500.0  221500.0  227900.0  237800.0
          Mount Olive        326300.0  330500.0  337200.0  341900.0  345000.0
          Dauphin Island     543700.0  539200.0  537500.0  537600.0  523800.0
          Tuscaloosa         334100.0  330000.0  332100.0  335700.0  333700.0
          Pleasant Grove     333800.0  333500.0  335200.0  337100.0  338700.0
          Edgewater               NaN       NaN       NaN       NaN       NaN
          Robertsdale        287300.0  288200.0  290300.0  289200.0  291900.0
          Elmore                  NaN       NaN       NaN       NaN       NaN
          Crane Hill              NaN       NaN       NaN       NaN       NaN
          Morris             374900.0  377100.0  380900.0  381900.0  384200.0
          Guntersville       283600.0  277800.0  284000.0  294400.0  299500.0
          Hope Hull          337000.0  339900.0  340500.0  342800.0  342600.0
          Elberta            427800.0  418100.0  428200.0  445400.0  443500.0
          Alabaster          375400.0  383300.0  381600.0  381900.0  384000.0
          Holly Pond              NaN       NaN       NaN       NaN       NaN
          Mount Vernon       152800.0  161000.0  163700.0  165800.0  163700.0
          Union Grove        269500.0  258300.0  264900.0  273900.0  274500.0
          Hoover             576900.0  576800.0  577800.0  579300.0  587700.0
          Center Point       253000.0  253400.0  256000.0  258300.0  259500.0
          Seminole           386300.0  372600.0  375700.0  386000.0  381100.0
          Chalkville         292300.0  295200.0  298100.0  299600.0  302200.0
          Priceville              NaN       NaN       NaN       NaN       NaN
          Hazel Green             NaN       NaN       NaN       NaN       NaN
          Summerdale         313900.0  300900.0  300500.0  297700.0  293600.0
          Calera             336600.0  343000.0  336400.0  334500.0  333700.0
          Vance              330400.0  324400.0  324400.0  329800.0  332100.0
          Ralph              399400.0  382200.0  381300.0  378700.0  376600.0
...                               ...       ...       ...       ...       ...
Wisconsin Menomonee Falls    500900.0  503800.0  511100.0  521500.0  522300.0
          Brookfield         643900.0  659900.0  679600.0  689400.0  679200.0
          Oak Creek          336500.0  340800.0  346400.0  349600.0  355300.0
          Barton                  NaN       NaN       NaN       NaN       NaN
          Roxbury            600300.0  611500.0  613500.0  632500.0  645100.0
          Cambria            271100.0  276100.0  279900.0  284400.0  291600.0
          Geneva             273200.0  283400.0  282600.0  284900.0  289200.0
          Sturtevant         275700.0  285100.0  288500.0  293600.0  299500.0
          Medina             564100.0  575000.0  579000.0  584800.0  595500.0
          Osborn             352700.0  366500.0  376200.0  379500.0  375900.0
          Sugar Creek        214200.0  217800.0  227100.0  230000.0  231300.0
          Utica              366600.0  376500.0  388100.0  379700.0  373100.0
          Rock               330000.0  336300.0  339400.0  338800.0  337400.0
          Eaton              445000.0  444000.0  442700.0  448500.0  447700.0
          Town of Eagle      538600.0  542400.0  551700.0  561400.0  561400.0
          Wales                   NaN       NaN       NaN       NaN       NaN
          Lisbon             638600.0  647300.0  644500.0  654200.0  655700.0
          Holmen                  NaN       NaN       NaN       NaN       NaN
          Holland            497200.0  504100.0  502200.0  497300.0  485900.0
          Lawrence           495900.0  496900.0  500700.0  508800.0  509100.0
          Whitelaw           344900.0  347000.0  347600.0  353300.0  350400.0
          Town of West Bend  396900.0  404700.0  406100.0  403600.0  398900.0
          Dunn               564300.0  576000.0  578100.0  591600.0  600200.0
          Bristol            595700.0  595800.0  599800.0  607100.0  620000.0
Wyoming   Casper             292900.0  298300.0  301900.0  305200.0  304600.0
          Burns              351600.0  353400.0  352900.0  352000.0  351700.0
          Pine Bluffs        313800.0  319500.0  312200.0  306700.0  310700.0
          Cheyenne           378900.0  379400.0  384400.0  385400.0  388900.0
          Evansville         394300.0  397200.0  400400.0  399900.0  393200.0
          Bar Nunn           299700.0  297300.0  295000.0  295900.0  302600.0

                              ...    2014q2  2014q3  2014q4  2015q1  2015q2  \
State     RegionName          ...
Alabama   Mulga               ...    136400  130800  126500  125800  128200
          Trussville          ...    636100  632900  643700  649800  660200
          Satsuma             ...    375800  382500  384800  387800  393900
          Irvington           ...    271600  287000  295400  298500  296400
          Mount Olive         ...    396200  397100  396200  406300  414300
          Dauphin Island      ...    636000  649600  661100  654400  666500
          Tuscaloosa          ...    413900  418700  428200  435000  434100
          Pleasant Grove      ...    365700  363700  361800  365900  371600
          Edgewater           ...    140200  134400  129900  126700  134800
          Robertsdale         ...    371600  376100  381700  383700  394900
          Elmore              ...    341900  345400  346200  349000  350700
          Crane Hill          ...    636300  644000  676600  668200  712300
          Morris              ...    454800  456400  464200  468100  469700
          Guntersville        ...    400500  408700  408300  415600  420800
          Hope Hull           ...    387200  390400  396300  412700  411400
          Elberta             ...    553900  542600  543500  546400  561600
          Alabaster           ...    441400  442900  446100  446700  448700
          Holly Pond          ...    295400  300300  310600  313500  320300
          Mount Vernon        ...    180600  175900  170000  167400  175000
          Union Grove         ...    353000  353500  349600  354200  362600
          Hoover              ...    730000  734600  742500  743700  743900
          Center Point        ...    236500  235300  240600  240300  240700
          Seminole            ...    501500  498600  504300  513300  519000
          Chalkville          ...    315700  313000  317600  320900  323000
          Priceville          ...    400700  385300  388900  402400  438100
          Hazel Green         ...    373300  371800  366300  367000  365800
          Summerdale          ...    410100  411200  408600  408900  413300
          Calera              ...    376600  380200  382900  385100  384100
          Vance               ...    379900  390900  401300  400500  400500
          Ralph               ...    464500  490800  495300  498200  507100
...                           ...       ...     ...     ...     ...     ...
Wisconsin Menomonee Falls     ...    624900  630200  634600  639200  647900
          Brookfield          ...    801200  804400  799100  807600  823500
          Oak Creek           ...    368500  373000  371000  382900  387300
          Barton              ...    667700  672900  682000  680300  687000
          Roxbury             ...    726400  728200  732900  733300  737900
          Cambria             ...    344400  361000  373500  371700  371100
          Geneva              ...    504300  519100  530700  521500  521000
          Sturtevant          ...    326600  336800  346400  343800  352200
          Medina              ...    722300  729000  735200  740900  749200
          Osborn              ...    519900  529700  540500  545900  546300
          Sugar Creek         ...    357200  370000  381600  375100  363800
          Utica               ...    492700  493400  490300  502000  505000
          Rock                ...    349300  353200  357800  359700  361200
          Eaton               ...    512400  546300  572700  582100  583000
          Town of Eagle       ...    759200  760400  758600  751800  750900
          Wales               ...    786400  786700  776000  769800  776000
          Lisbon              ...    770300  759400  753900  755700  765700
          Holmen              ...    431500  459700  480700  491600  494300
          Holland             ...    603800  604700  603800  618000  622800
          Lawrence            ...    611000  622500  630100  638000  644300
          Whitelaw            ...    361300  365100  368300  365800  360100
          Town of West Bend   ...    466000  470200  472200  471600  471500
          Dunn                ...    769800  775800  785200  789500  795900
          Bristol             ...    657800  669000  687500  708700  715800
Wyoming   Casper              ...    527300  531900  543000  546200  547900
          Burns               ...    506600  485800  481300  487800  489200
          Pine Bluffs         ...    446000  463100  474300  491700  502300
          Cheyenne            ...    532400  530200  536300  545100  549800
          Evansville          ...    890200  917000  928500  921900  909500
          Bar Nunn            ...    597700  602800  603400  620000  626600

                             2015q3  2015q4  2016q1  2016q2  2016q3
State     RegionName
Alabama   Mulga              126100  129100  122000  115100   76600
          Trussville         659500  658300  660800  670700  451200
          Satsuma            400000  404400  404000  400600  266200
          Irvington          292800  294000  304500  311900  207900
          Mount Olive        415300  421900  428600  432100  287700
          Dauphin Island     705500  718300  719300  714400  488400
          Tuscaloosa         432800  435000  420900  414100  277300
          Pleasant Grove     375800  382700  389800  386500  259900
          Edgewater          138100  142500  143800  144200   95500
          Robertsdale        407300  412100  414500  408500  267700
          Elmore             349700  352500  349000  347000  232700
          Crane Hill         719100  728300  695100  688200  472700
          Morris             473900  473800  476900  478400  318200
          Guntersville       428700  432500  430400  434200  290000
          Hope Hull          408000  396800  401100  403800  271600
          Elberta            572700  591300  601300  593800  390300
          Alabaster          451100  455200  460400  465300  311700
          Holly Pond         325300  325900  318600  315500  216800
          Mount Vernon       177000  177100  179600  179900  121300
          Union Grove        369200  369000  364500  357200  239600
          Hoover             746300  750600  761800  773700  519900
          Center Point       243000  242700  246100  249100  168000
          Seminole           516300  521300  524000  531400  359200
          Chalkville         329000  333400  335500  343200  231400
          Priceville         462900  450700  445500  437100  289300
          Hazel Green        362800  366200  370700  373400  251800
          Summerdale         423700  434200  437800  439500  291900
          Calera             384600  385600  388900  389800  259200
          Vance              406700  411600  403000  400800  262300
          Ralph              515600  562100  548900  529400  332700
...                             ...     ...     ...     ...     ...
Wisconsin Menomonee Falls    658700  664600  671800  682500  462900
          Brookfield         838000  847800  854800  863500  582300
          Oak Creek          390100  401900  410000  409200  265400
          Barton             692900  701900  704900  716400  491400
          Roxbury            746900  761400  770800  779000  532700
          Cambria            378000  378600  373700  385500  266200
          Geneva             533600  538100  546100  554100  375700
          Sturtevant         346200  335100  335700  347600  237600
          Medina             757600  768900  779800  787200  530800
          Osborn             551100  561900  575600  602500  413900
          Sugar Creek        368200  377400  385800  406300  280000
          Utica              498100  481500  478700  479100  327900
          Rock               364300  375500  384700  392900  273100
          Eaton              581000  584900  579400  588800  401100
          Town of Eagle      748500  757000  752900  769300  531500
          Wales              784200  800700  805300  827000  564800
          Lisbon             782900  794100  803300  817100  558000
          Holmen             493600  498100  504700  506300  334000
          Holland            638600  653500  665900  684100  469900
          Lawrence           653400  662100  672900  684200  462500
          Whitelaw           351800  353300  351700  352200  235200
          Town of West Bend  479800  488800  496900  510800  346000
          Dunn               802100  821700  830000  842900  577700
          Bristol            718700  720400  733400  745100  503300
Wyoming   Casper             549900  548100  553000  555500  368700
          Burns              493800  492900  504800  514800  341000
          Pine Bluffs        502400  507600  500500  491400  315300
          Cheyenne           560300  572000  583300  589500  398200
          Evansville         902900  912600  928300  927600  618100
          Bar Nunn           635400  635400  630600  626500  414900

[10730 rows x 67 columns]

In [420]:
from scipy import stats

def run_ttest():
    '''First creates new data showing the decline or growth of housing prices
    between the recession start and the recession bottom. Then runs a ttest
    comparing the university town values to the non-university towns values, 
    return whether the alternative hypothesis (that the two groups are the same)
    is true or not as well as the p-value of the confidence. 
    
    Return the tuple (different, p, better) where different=True if the t-test is
    True at a p<0.01 (we reject the null hypothesis), or different=False if 
    otherwise (we cannot reject the null hypothesis). The variable p should
    be equal to the exact p value returned from scipy.stats.ttest_ind(). The
    value for better should be either "university town" or "non-university town"
    depending on which has a lower mean price ratio (which is equivilent to a
    reduced market loss).'''
    #restrincting housing prices data to just prices during the recession
    housing_prices = convert_housing_data_to_quarters()
    recession_start = get_recession_start()
    recession_start_id = housing_prices.columns.get_loc(recession_start)
    recession_end = get_recession_end()
    recession_end_id = housing_prices.columns.get_loc(recession_end)+1
    recession_housing_prices = housing_prices.iloc[:,recession_start_id:recession_end_id]
    
    #Creating a new dataframe that is just housing prices of university towns
    recession_housing_prices = recession_housing_prices.reset_index()
    university_towns = get_list_of_university_towns()
    
    university_towns_prices = pd.merge(recession_housing_prices, university_towns, how='inner').dropna()
    university_towns_prices = university_towns_prices.set_index(['State','RegionName'])
    recession_housing_prices = recession_housing_prices.set_index(['State','RegionName'])
    
    #Removing university towns from the main housing prices df
    non_university_prices = recession_housing_prices[~recession_housing_prices.isin(university_towns_prices)].dropna()
    
    
    hypothesis_test = stats.ttest_ind(university_towns_prices[[get_recession_bottom()]],non_university_prices[[get_recession_bottom()]])
    
    difference = hypothesis_test.pvalue[0]<0.01
    
    non_univ_mean =  non_university_prices[[get_recession_bottom()]].mean()[0]
    
    univ_mean = university_towns_prices[[get_recession_bottom()]].mean()[0]
    
    if univ_mean < non_univ_mean:
        better = 'university town'
    else:
        better = 'non-university town'
    
    result = (difference, hypothesis_test.pvalue[0],better)
    
    return result
run_ttest()

(False, 0.029515311704715066, 'university town')